### PR TITLE
Ensure there is no caching on the module

### PR DESCRIPTION
**Pull request by wilsonge**
This *should* fix https://joomjunk.co.uk/forum/jj-shoutbox/1280-disable-or-clear-cache-after-submit.html#2606 however I need to do some testing (this is totally untested at the moment) - it might need us to make an appropriate change in script.php as well

### CODE REVIEW

**Comment by lsquall17** [comment]
Hi, i try it now and thats not work... 
But some modules use this code:
        // check cache was endable ?
        if ($params->get('enable_cache')) {
            $cache = JFactory::getCache();
            $cache->setCaching(true);
            $cache->setLifeTime($params->get('cache_time', 30) * 60);
            $rows = $cache->get(array($this, 'getArticles'), array($params));
        } else {
            $rows = $this->getArticles($params);
        }

**Comment by C-Lodder** [comment]
@lsquall17 - Hey, once you tried adding the fix, did you go to the Shoutbox options in the Joomla backend, click save, set the caching the none, then click save again?

**Comment by lsquall17** [comment]
@C-Lodder Yes, i try it again - add fix -> go backend -> set none caching  -> save -> again check nocache -> save again -> testing, noting change. 

If you want i can give you access to my VPS server.

**Comment by wilsonge** [comment]
Hi,
If you change the name of this param from `cache` to `owncache` does that work? (see the change I've just made to the PR.

**Pull request merged**
