### PR TITLE
Append modal before closing body tag

### PR DESCRIPTION
**Pull request by C-Lodder**
@wilsonge - Please test when you get a chance. Working my end....finally

### CODE REVIEW

**Comment by wilsonge** [comment]
Not successful for me :(

I just installed this on a fresh copy of Joomla and got the following:

```
( ! ) Notice: Undefined variable: image in C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\helper.php on line 1210
Call Stack
#	Time	Memory	Function	Location
1	0.1119	148352	{main}( )	..\index.php:0
2	0.2596	2541600	JApplicationCms->execute( )	..\index.php:49
3	1.0641	7567368	JApplicationSite->render( )	..\cms.php:263
4	1.0646	7567760	JApplicationCms->render( )	..\site.php:745
5	1.0897	7839048	JDocumentHtml->render( )	..\cms.php:1068
6	1.0897	7839056	JDocumentHtml->_renderTemplate( )	..\html.php:477
7	1.0937	7867928	JDocumentHtml->getBuffer( )	..\html.php:697
8	1.0937	7868120	JDocumentRendererHtmlModules->render( )	..\html.php:411
9	1.3921	8005656	JDocumentRendererHtmlModule->render( )	..\modules.php:42
10	1.3941	8071800	JModuleHelper::renderModule( )	..\module.php:93
11	1.4032	8168072	include( 'C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\mod_shoutbox.php' )	..\helper.php:190
12	1.4394	8429864	require( 'C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\tmpl\default.php' )	..\mod_shoutbox.php:248
13	1.5658	8777824	ModShoutboxHelper->renderHistoryModal( )	..\default.php:330

( ! ) Notice: Undefined variable: title in C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\layouts\history.php on line 20
Call Stack
#	Time	Memory	Function	Location
1	0.1119	148352	{main}( )	..\index.php:0
2	0.2596	2541600	JApplicationCms->execute( )	..\index.php:49
3	1.0641	7567368	JApplicationSite->render( )	..\cms.php:263
4	1.0646	7567760	JApplicationCms->render( )	..\site.php:745
5	1.0897	7839048	JDocumentHtml->render( )	..\cms.php:1068
6	1.0897	7839056	JDocumentHtml->_renderTemplate( )	..\html.php:477
7	1.0937	7867928	JDocumentHtml->getBuffer( )	..\html.php:697
8	1.0937	7868120	JDocumentRendererHtmlModules->render( )	..\html.php:411
9	1.3921	8005656	JDocumentRendererHtmlModule->render( )	..\modules.php:42
10	1.3941	8071800	JModuleHelper::renderModule( )	..\module.php:93
11	1.4032	8168072	include( 'C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\mod_shoutbox.php' )	..\helper.php:190
12	1.4394	8429864	require( 'C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\tmpl\default.php' )	..\mod_shoutbox.php:248
13	1.5658	8777824	ModShoutboxHelper->renderHistoryModal( )	..\default.php:330
14	1.6156	8796912	JLayoutFile->render( )	..\helper.php:1222
15	1.6189	8823032	include( 'C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\layouts\history.php' )	..\file.php:121
```

**Comment by wilsonge** [comment]
Not successful for me :(

I just installed this on a fresh copy of Joomla and got the following:

```
( ! ) Notice: Undefined variable: image in C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\helper.php on line 1210
Call Stack
#	Time	Memory	Function	Location
1	0.1119	148352	{main}( )	..\index.php:0
2	0.2596	2541600	JApplicationCms->execute( )	..\index.php:49
3	1.0641	7567368	JApplicationSite->render( )	..\cms.php:263
4	1.0646	7567760	JApplicationCms->render( )	..\site.php:745
5	1.0897	7839048	JDocumentHtml->render( )	..\cms.php:1068
6	1.0897	7839056	JDocumentHtml->_renderTemplate( )	..\html.php:477
7	1.0937	7867928	JDocumentHtml->getBuffer( )	..\html.php:697
8	1.0937	7868120	JDocumentRendererHtmlModules->render( )	..\html.php:411
9	1.3921	8005656	JDocumentRendererHtmlModule->render( )	..\modules.php:42
10	1.3941	8071800	JModuleHelper::renderModule( )	..\module.php:93
11	1.4032	8168072	include( 'C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\mod_shoutbox.php' )	..\helper.php:190
12	1.4394	8429864	require( 'C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\tmpl\default.php' )	..\mod_shoutbox.php:248
13	1.5658	8777824	ModShoutboxHelper->renderHistoryModal( )	..\default.php:330

( ! ) Notice: Undefined variable: title in C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\layouts\history.php on line 20
Call Stack
#	Time	Memory	Function	Location
1	0.1119	148352	{main}( )	..\index.php:0
2	0.2596	2541600	JApplicationCms->execute( )	..\index.php:49
3	1.0641	7567368	JApplicationSite->render( )	..\cms.php:263
4	1.0646	7567760	JApplicationCms->render( )	..\site.php:745
5	1.0897	7839048	JDocumentHtml->render( )	..\cms.php:1068
6	1.0897	7839056	JDocumentHtml->_renderTemplate( )	..\html.php:477
7	1.0937	7867928	JDocumentHtml->getBuffer( )	..\html.php:697
8	1.0937	7868120	JDocumentRendererHtmlModules->render( )	..\html.php:411
9	1.3921	8005656	JDocumentRendererHtmlModule->render( )	..\modules.php:42
10	1.3941	8071800	JModuleHelper::renderModule( )	..\module.php:93
11	1.4032	8168072	include( 'C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\mod_shoutbox.php' )	..\helper.php:190
12	1.4394	8429864	require( 'C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\tmpl\default.php' )	..\mod_shoutbox.php:248
13	1.5658	8777824	ModShoutboxHelper->renderHistoryModal( )	..\default.php:330
14	1.6156	8796912	JLayoutFile->render( )	..\helper.php:1222
15	1.6189	8823032	include( 'C:\VirtualHost\joomla350.testing.org\joomla-cms\modules\mod_shoutbox\layouts\history.php' )	..\file.php:121
```

**Comment by wilsonge** [comment]
OK So as an update for this - the image variable appears to be unused so we should remove it BUT the title thing is being used - so not sure what you're planning there :(

**Comment by C-Lodder** [comment]
Hmm odd. Will double check today and update the PR

**Comment by C-Lodder** [comment]
@wilsonge - Fixed the PHP errors. Image modal now working but History isn't

**Comment by C-Lodder** [comment]
@wilsonge - All fixed and working

**Comment by wilsonge** [comment]
In Basingstoke with parents now. Remind me to try again this afternoon

**Pull request merged**
